# Generated by Django 2.2.1 on 2019-05-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock2',
            new_name='stock',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
